model:
  _target_: model.CrossAttentionClassifier
  hidden_dim: 256
  input_dim: 768
  num_heads: 4
  dropout: 0.5

train:
  seed: 42
  lr: 1e-6
  decay: 1e-5
  epoch: 50
  batch: 64
  use_fp16: true
